name: snooze_slayer
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  analog_clock: ^0.1.1
  google_nav_bar: ^5.0.6
  flutter_bloc: ^8.1.3
  flutter_neumorphic: ^3.2.0
  path_provider: ^2.1.1
  alarm: ^3.0.0-dev.6
  path: ^1.8.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  freezed_annotation: ^2.4.1
  permission_handler: ^11.0.1

dependency_overrides:
  alarm:
    path: package_overrides/alarm-3.0.0-dev.4/
  flutter_neumorphic:
    path: package_overrides/flutter_neumorphic-3.2.0/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  freezed: ^2.4.5


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audio/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
